In [1]:
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd

In [2]:
df = pd.read_csv('loan_approval_dataset.csv')
X = df.drop(columns='Loan_Approved')
y= df.Loan_Approved
df

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Residence_Type,Previous_Default,Loan_Approved
0,56,136748,584,38209,36 months,Employed,Owned,Yes,Yes
1,46,25287,815,27424,24 months,Self-Employed,Rented,No,Yes
2,32,146593,398,42396,12 months,Unemployed,Rented,Yes,Yes
3,60,54387,696,11370,24 months,Unemployed,Owned,No,No
4,25,28512,788,14528,12 months,Employed,Owned,No,No
...,...,...,...,...,...,...,...,...,...
995,22,49241,500,41020,24 months,Self-Employed,Owned,No,Yes
996,40,116214,423,12415,48 months,Self-Employed,Owned,No,Yes
997,27,64569,300,28155,36 months,Self-Employed,Rented,Yes,Yes
998,61,31745,490,48884,12 months,Self-Employed,Mortgage,No,Yes
999,19,46029,815,21964,24 months,Employed,Mortgage,Yes,No

In [3]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y,train_size=0.8,random_state=42)

In [4]:
num_cols= ['Age','Salary']
obj_cols= X.select_dtypes(exclude='number').columns

In [5]:
preprocessing = ColumnTransformer(
    transformers=[
        ('scaling',StandardScaler(),num_cols),
        ('encoder',OneHotEncoder(),obj_cols)
    ],
    remainder='passthrough'
)
values=preprocessing.fit_transform(xtrain)

In [6]:
values=preprocessing.fit_transform(xtrain)
columnnames = preprocessing.get_feature_names_out()
xtrain = pd.DataFrame(data=values,columns=columnnames)

In [7]:
xtrain

,scaling__Age,scaling__Salary,encoder__Loan_Term_12 months,encoder__Loan_Term_24 months,encoder__Loan_Term_36 months,encoder__Loan_Term_48 months,encoder__Employment_Status_Employed,encoder__Employment_Status_Self-Employed,encoder__Employment_Status_Unemployed,encoder__Residence_Type_Mortgage,encoder__Residence_Type_Owned,encoder__Residence_Type_Rented,encoder__Previous_Default_No,encoder__Previous_Default_Yes,remainder__Credit_Score,remainder__Loan_Amount
0,0.217341,0.001268,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,507.0,17109.0
1,-0.222472,0.049597,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,489.0,10776.0
2,0.290643,-0.930762,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,762.0,39441.0
3,0.437247,-0.261695,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,809.0,40596.0
4,0.363945,0.409350,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,504.0,31956.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,0.803758,0.867453,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,689.0,31649.0
796,-1.102097,1.308093,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,388.0,22514.0
797,1.683383,1.291202,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,683.0,8642.0
798,-1.102097,-0.976906,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,841.0,45697.0
799,-0.955493,-0.156500,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,306.0,11581.0