In [102]:
import pandas as pd
from sklearn.linear_model import Ridge,Lasso,ElasticNet,LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error

In [103]:
''' 
Regularization types or parameters
What is weights ?
It tells the importance of features(columns)
Lasso ?(L1) |w|
it pushes the weights towards to zero,and exactly zero
if its weights are exactly zero those columns are not important
when to use Lasso ?
    -When we have more features and model is overfit
Ridge(L2) ? w²
It shrinks the weights but never force them to zero
when to use Ridge ?
When model is overfit and multicollinearity
ElasticNet(L1+L2) ?
It uses both lasso and ridge with the help of l1_ratio
it selects important features and also handles multicollinearity
when to use ElasticNet?
    when feature selection(more no of features) and 
    multicollinearity problem occurs.
    when ridge and lasso fails in overfit
cost function ?
MSE is a cost function in regression which calculates errors 
during model training
'''

' \nRegularization types or parameters\nWhat is weights ?\nIt tells the importance of features(columns)\nLasso ?(L1) |w|\nit pushes the weights towards to zero,and exactly zero\nif its weights are exactly zero those columns are not important\nwhen to use Lasso ?\n    -When we have more features and model is overfit\nRidge(L2) ? w²\nIt shrinks the weights but never force them to zero\nwhen to use Ridge ?\nWhen model is overfit and multicollinearity\nElasticNet(L1+L2) ?\nIt uses both lasso and ridge with the help of l1_ratio\nit selects important features and also handles multicollinearity\nwhen to use ElasticNet?\n    when feature selection(more no of features) and \n    multicollinearity problem occurs.\n    when ridge and lasso fails in overfit\ncost function ?\nMSE is a cost function in regression which calculates errors \nduring model training\n'

In [104]:
df = pd.read_csv('Student_Performance.csv')

In [105]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [106]:
df.corr(numeric_only=True)['Performance Index']

Hours Studied                       0.373730
Previous Scores                     0.915189
Sleep Hours                         0.048106
Sample Question Papers Practiced    0.043268
Performance Index                   1.000000
Name: Performance Index, dtype: float64

In [107]:
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes':1,'No':0})

In [108]:
df.drop(columns='Performance Index')

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5
...,...,...,...,...,...
9995,1,49,1,4,2
9996,7,64,1,8,5
9997,6,83,1,8,5
9998,9,97,1,7,0
9999,7,74,0,8,1

In [109]:
# df = df.drop(columns='Previous Scores')

In [110]:
X = df.drop(columns='Performance Index')
# X = df[['Hours Studied','Previous Scores']]
y = df['Performance Index']

In [111]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,random_state=42,train_size=0.8)

In [112]:
model = LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [113]:
model.coef_

array([2.85248393, 1.0169882 , 0.60861668, 0.47694148, 0.19183144])

In [114]:
model.score(xtrain,ytrain)

0.9886898790682355

In [115]:
model.score(xtest,ytest)

0.9889832909573145

In [116]:
#train data
#actual output =>ytrain
#predicted output => model.predict(xtrain)
ypred_train = model.predict(xtrain)
r2_score(ytrain,ypred_train)

0.9886898790682355

In [117]:
#test data
#actual output =>ytest
#predicted output => model.predict(xtest)
ypred_test = model.predict(xtest)
r2_score(ytest,ypred_test)

0.9889832909573145

In [118]:
model1  = Ridge()
model1.fit(xtrain,ytrain)
model1.coef_

array([2.85243127, 1.01698772, 0.60831192, 0.47691959, 0.19182918])

In [119]:
model1.score(xtrain,ytrain)

0.9886898789505935

In [120]:
model1.score(xtest,ytest)

0.9889832645273239

In [122]:
model2 = ElasticNet(l1_ratio=0.3)
model2.fit(xtrain,ytrain)

ElasticNet(l1_ratio=0.3)

In [123]:
model2.coef_

array([2.54497147, 1.01325493, 0.        , 0.29993934, 0.14676719])