In [183]:
# pip install category_encoders

In [184]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split

In [185]:
df = pd.read_csv('Student_Performance.csv')
df

      Hours Studied  ...  Performance Index
0                 7  ...               91.0
1                 4  ...               65.0
2                 8  ...               45.0
3                 5  ...               36.0
4                 7  ...               66.0
...             ...  ...                ...
9995              1  ...               23.0
9996              7  ...               58.0
9997              6  ...               74.0
9998              9  ...               95.0
9999              7  ...               64.0

[10000 rows x 6 columns]

In [186]:
X = df.drop(columns=['Performance Index'])
y = df['Performance Index']

In [187]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,random_state=42,train_size=0.8)

In [188]:
# encoder = LabelEncoder()
# xtrain['Extracurricular Activities'] =encoder.fit_transform(xtrain['Extracurricular Activities'])
# xtest['Extracurricular Activities'] =encoder.transform(xtest['Extracurricular Activities'])

In [189]:
# encoder.transform(['OK'])

In [190]:
encode = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
# encode.fit_transform(xtrain['Extracurricular Activities'])
# ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [191]:
# xtrain[['Extracurricular Activities_No', 'Extracurricular Activities_Yes']]=encode.fit_transform(xtrain[['Extracurricular Activities']])
# xtrain.drop(columns='Extracurricular Activities',inplace=True)

In [192]:
# encode.get_feature_names_out()

In [193]:
# encode.transform([['OK'],['No']])

In [194]:
encode = OrdinalEncoder(categories=[['Yes','No']],handle_unknown='use_encoded_value',unknown_value=-1)

encode.fit_transform(xtrain[['Extracurricular Activities']])

array([[1.],
       [0.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], shape=(8000, 1))

In [195]:
encode.get_feature_names_out()

array(['Extracurricular Activities'], dtype=object)

In [196]:
encode.transform([['Yesss']])

c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[-1.]])

In [197]:
encoder = TargetEncoder()

encoder.fit_transform(xtrain['Extracurricular Activities'],ytrain)

      Extracurricular Activities
9254                   54.956468
1561                   55.674248
1670                   54.956468
6087                   54.956468
6669                   54.956468
...                          ...
5734                   55.674248
5191                   54.956468
5390                   54.956468
860                    54.956468
7270                   54.956468

[8000 rows x 1 columns]

In [ ]:
'''
input | output
--------------
Yes   | 100
No    | 80
Yes   | 70
Yes   | 100
No    | 80

Yes -> 100,70,100 => 270/3 = >90
No -> 80,80 => 160/2 => 80


'''

In [198]:
df_cat = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red'],
    'Shape': ['Circle', 'Square', 'Triangle', 'Circle'],
    'Target': [10.5, 20.0, 15.0, 12.5]
})
df_cat

   Color     Shape  Target
0    Red    Circle    10.5
1   Blue    Square    20.0
2  Green  Triangle    15.0
3    Red    Circle    12.5

In [201]:
encoder = TargetEncoder()
encoder.fit_transform(df_cat[['Color','Shape']],df_cat['Target'])

       Color      Shape
0  14.074447  14.074447
1  15.215597  15.215597
2  14.565054  14.565054
3  14.074447  14.074447